### ISSUE TITLE
[FEATURE] ldap search

### ISSUE THREAD

**Issue by christopherpickering** [atlas-bi/LDAP-ETL#66]
- [x] I've searched the issues
- [x] I've read the [docs](https://www.atlas.bi/docs/)

## Feature Request

It would be nice to use a ldap search query to pull in users instead of having to specify multiple bases.

**Comment by christopherpickering** [comment]
Nice! thanks for the example! Are you running the other etls? It would be great to talk more sometime.

**Comment by christopherpickering** [comment]
@paysni I would appreciate it if you could check out the [dev](https://github.com/atlas-bi/LDAP-ETL/tree/dev) branch. 

I renamed most of the env vars, changed to ldap search strings, added profile photos, and clean up some junk.

The cn and ou regexs in the user section can probably be replaced with the utils function from the ldad3 libaray to be a bit cleaner, but maybe another day.

**Comment by paysni** [comment]
@christopherpickering it works for us. I like being able to choose the fields in the .env file. For example we store phone in telephoneNumber field before ipPhone. 

I noticed you had LDAP_USER_SEARCH twice in your example .env file but that doesn't cause an issue. Might want to remove it though.

We are also using all the Tableau ETL, Solr-Search ETL, and bi-library ETL package. It would be great to talk more sometime. I can be reached at payton_snider@valleymed.org

**Comment by christopherpickering** [comment]
> I noticed you had LDAP_USER_SEARCH twice in your example .env file but that doesn't cause an issue. Might want to remove it though.

ops, thanks!
